# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a56b126848dd3191684637966463a1f262166145a1ca6b9854839f200e5fe69ce8df593a6ce59570eda73e70890384df292eb5a2f1611c5533fee65e4d65e9be

test:
  secret_key_base: b52d7b887bb7b540cb595b496a055eb92c8fb5280035a52655dbc594a6c81aeaec723a74b3c82cf4228cb96fabf9d3242ff72d34c62804505583498f78e8b666

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
